### ISSUE TITLE
4.0 beta, service unavailable

### ISSUE THREAD

**Issue by tanthammar** [versionpress/versionpress#1296] opened 2017-10-12 09:14 UTC
Tried multiple times on different days to activate the plugin.
versionpress 4.0 beta
wp 4.8.2
git-version' => '2.14.1'

After a "very" long time I get this message:

> VersionPress Activation
> Setting things up for you. It may take a while, please be patient.
> 
> Environment set to 'dev'
> Starting up
> Helper database tables created
> Service Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Any suggestions?

**Comment by pavelevap** [comment] 2018-05-07 09:34
Hi @tanthammar,

this problem is usually caused by large database or plugin conflict, see related [issue](https://github.com/versionpress/support/issues/50).
Did you try to use clean install if it works?
How large is your database and how many active plugins?

This a support question and I am closing this issue for now, please create another one in [support repo](https://github.com/versionpress/support/) if you have additional info or need further assistance.

**Closed by pavelevap** 2018-05-07 09:34 UTC
