### ISSUE TITLE
dateModifiedMergesAutomatically test is failing

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1382] opened 2019-03-05 19:44 UTC
Running `npm run tests:custom-with-wordpress -- -c phpunit.xml --filter dateModifiedMergesAutomatically` leads to a following problem:

```
VersionPress\Tests\Workflow\CloneMergeTest::dateModifiedMergesAutomatically
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'2019-03-05 10:27:39
+'2019-03-05 10:25:58
/opt/versionpress/tests/Workflow/CloneMergeTest.php:146
```

I checked `wptest` and `wptestclone` repositories after the test:

- 10:45 - VersionPress activated on `wptest` (by WP-CLI).
- 10:47 - Page `E02347A1732744B1B94B3530FA83EB9B` [created](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/tests/Workflow/CloneMergeTest.php#L105) with defined `post_title` "Test page for menu" and `post_content` "Test page" (by WP-CLI).
- 10:47 - 11:26 - Clone `wptestclone` created (I restricted memory for my Virtualbox, so it was really slow).
- 11:26 - Page `E02347A1732744B1B94B3530FA83EB9B` [updated](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/tests/Workflow/CloneMergeTest.php#L114) `post_title` to "Some new title" and `date_modified` correctly set to `2019-03-05 10:25:58` (by WP-CLI).
- 11:28 - Page `E02347A1732744B1B94B3530FA83EB9B` [updated](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/tests/Workflow/CloneMergeTest.php#L125) `post_content` to "Some new content" for `wptestclone` and `date_modified` correctly set to `2019-03-05 10:27:39` (by WP-CLI).
- Next `git pull` was [running](https://github.com/versionpress/versionpress/blob/b14fe014360ae36597ac2fd18effa801de566f31/plugins/versionpress/tests/Workflow/CloneMergeTest.php#L130), commit from `wptestclone` was fetched, with `post_content` and `post_modified` changed + merge commit was created (by user `test`) where only `post_content` was merged :-(

:question: Interesting that similar test `mergedDatesWithoutConflict` from [GitRepository](https://github.com/versionpress/versionpress/blob/e2209836d30889727991365fde2c983d0121e5a1/plugins/versionpress/tests/GitRepositoryTests/MergeDriverTest.php#L133) works well :thinking: 

Bash version of VersionPress merge driver was used automatically.

```
[merge "vp-ini"]
name = VersionPress ini merge driver
driver = /var/www/html/wptest/wp-content/plugins/versionpress/src/Git/merge-drivers/ini-merge.sh %O %A %B
recursive = text
```

:question:  When I force test to use PHP implementation of merge driver, then test will pass :thinking: 

```
[merge "vp-ini"]
name = VersionPress ini merge driver
driver = "/usr/local/bin/php" "/var/www/html/wptest/wp-content/plugins/versionpress/src/Git/merge-drivers/ini-merge.php" %O %A %B
recursive = text
```

**Comment by borekb** [comment] 2019-03-05 22:08
Thanks, @pavelevap, that's great information that actually lead us to the root cause which is #1384. I'm going to close this as the test will start working again when that issue is fixed.

**Closed by borekb** 2019-03-05 22:08 UTC
Labels: scope: tests
