### ISSUE TITLE
Undo does not work for added postmeta

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#876] opened 2016-04-06 19:50 UTC
When I try to undo commit related to added postmeta, I get following error: `Error: Overwritten changes can not be reverted.`

Steps to reproduce:

1) Add any postmeta to any post: commit "Created postmeta AB for post CD".
2) Save (update) this post: commit "Updated post CD".
3) Try to undo first postmeta commit.

Related question: Should we commit every post update even if only `post_modified` was changed? It can lead to many commits without relevant values.

**Comment by JanVoracek** [comment] 2016-04-07 09:05
I cannot reproduce it. However, it will be probably solved by #883.

Re `post_modified`: We need to save every change. WordPress displays the `modification_date` with a post and if you updates the post and push the changes, the environments should look exactly the same. Maybe we will not display those commits in the table one day but we need to do them.

**Comment by borekb** [comment] 2016-04-07 11:29
I can reproduce it:

![image](https://cloud.githubusercontent.com/assets/101152/14349575/499bb5e4-fcc4-11e5-89ca-6c849e26280c.png)

I see no reason why change no. 2 should not be able to be undone, and it works fine on @JanVoracek's laptop (Mac OS). Maybe it's an issue on Windows and in the PHP implementation of the merge driver (#588)? Any ideas, @octopuss?

**Comment by octopuss** [comment] 2016-04-07 12:24
@borekb i'll look at it.

**Comment by octopuss** [comment] 2016-04-07 13:19
So I've performed some tests, and it is not connected with merge driver. Merge driver is not called during simple `commit` performed when *undo* is pressed. 

Moreover I was unable to reproduce it on my Macbook :negative_squared_cross_mark:

**Comment by pavelevap** [comment] 2016-04-07 18:45
OK, I will try to debug what is going on on my machine...

**Comment by pavelevap** [comment] 2016-04-08 10:55
So, my [$output](https://github.com/versionpress/versionpress/blob/50f95bccdf2b3ed531c9129cf060dbe26ba8e32b/plugins/versionpress/src/Git/GitRepository.php#L232) is following:

```
error: cannot spawn sh: No such file or directory
fatal: Failed to execute internal merge
```

I also tried a command line: `git revert -n 01063771e4ef74bf224bfa7fa402b88b8a030716`

```
error: could not revert <commit hash> <commit message>
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
```

Also in `.git/MERGE_MSG` I have following:

```
# Conflicts:
# wp-content/vpdb/posts/B4/B4D018D7EE754AFFB97C023BC61439D9.ini
```

I can undo any other commit, only added postmeta does not work, strange. Any ideas what is wrong or what should I check?

**Comment by octopuss** [comment] 2016-04-08 11:00
That's weird seems like you have bash merge driver installed instead of php
one.

On Friday, 8 April 2016, pavelevap <notifications@github.com> wrote:

> So, my $output
> <https://github.com/versionpress/versionpress/blob/50f95bccdf2b3ed531c9129cf060dbe26ba8e32b/plugins/versionpress/src/Git/GitRepository.php#L232>
> is following:
>
> error: cannot spawn sh: No such file or directory
> fatal: Failed to execute internal merge
>
> I also tried a command line: git revert -n
> 01063771e4ef74bf224bfa7fa402b88b8a030716
>
> error: could not revert <commit hash> <commit message>
> hint: after resolving the conflicts, mark the corrected paths
> hint: with 'git add <paths>' or 'git rm <paths>'
>
> Also in .git/MERGE_MSG I have following:
>
> # Conflicts:
> # wp-content/vpdb/posts/B4/B4D018D7EE754AFFB97C023BC61439D9.ini
>
> I can undo any other commit, only added postmeta does not work, strange.
> Any ideas what is wrong or what should I check?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/versionpress/versionpress/issues/876#issuecomment-207375306>
>


-- 
S pozdravom a pekný deň praje,
Ing. Ivan Doležal
http://www.octopuss.sk

**Comment by pavelevap** [comment] 2016-04-08 11:56
@octopuss: I am not sure what do you exactly mean :-) but it has to be somehow connected to a new merge driver. Whenever post is modified (`post_modified` value changed), no previous change of this post can be reverted (it is not related only to adding postmeta as I supposed earlier). And another hint is Windows :-)

**Comment by pavelevap** [comment] 2016-04-08 12:07
@JanVoracek: Re `post_modified`: Yes, but I thought about changes where only `post_modified` is changed. There is no need to track (and commit) these changes because nothing was really changed? Users do not care about this date when it does not mean anything? Even if WordPress changes this value, there is no reason for VP (and also for real user) to use it, I guess. Instead, it could be helpful to change `post_modified` when for example postmeta are updated. But we can create another discussion issue for it if you find it interesting.

**Comment by octopuss** [comment] 2016-04-08 13:29
@pavelevap : we have two implemetations of custom merge driver. They are platform specific, and correct one is installed when VersionPress is activated and Git repository is initialized (see https://github.com/versionpress/versionpress/blob/master/plugins/versionpress/src/Git/MergeDriverInstaller.php#L89-L96). Your error implies that wrong one was installed on your Windows machine.

**Comment by pavelevap** [comment] 2016-04-08 13:49
OK, thank you. I only installed latest VP version `3.0-beta`.

```
[merge "vp-ini"]
        name = VersionPress ini merge driver
        driver = "C:/xampp/apache/bin/httpd.exe" "C:/www/wp44/wp-content/plugins/versionpress/src/Git/merge-drivers/ini-merge.php" %O %A %B
        recursive = text
```

**Comment by borekb** [comment] 2016-04-08 15:06
What the hell :) PHP path detection failed. We should ban mod_php, it's just wrong.

**Comment by octopuss** [comment] 2016-04-11 06:33
@pavelevap : could you try this fragment of code, if it returns correct php path ? 

http://stackoverflow.com/a/32997437

**Comment by borekb** [comment] 2016-04-11 13:55
It's `httpd.exe` on my machine too, and when I think about it it probably makes sense. When PHP runs as `mod_php`, it's just some DLL loaded into the Apache process, and there's no way it could report a path to `php.exe` which might not even exist on the disk.

We need to replace the `PHP_BINARY` detection by something more clever. I think that we could use `extension_dir` – this directory usually resides in the PHP installation directory so could be quite reliable. I'll take this issue and try it.

**Closed** 2016-04-14 10:38 UTC
Labels: bug, in review, scope:core
