### ISSUE TITLE
Clean up temp folder

### ISSUE THREAD

**Issue by pavelevap** [versionpress/versionpress#1192] opened 2017-03-13 21:07 UTC
We should automatically remove everything from `temp` folder during build, except versioned [files](https://github.com/versionpress/versionpress/tree/master/plugins/versionpress/temp).

@vasek17 mentioned similar [condition](https://github.com/versionpress/versionpress/blob/325cd8335b4083a17d2e489c5b72b018f7f103eb/gulpfile.js#L116) on Slack as an example.

**Comment by pavelevap** [comment] 2017-03-13 21:20
Probably also remove `.DS_Store` from main folder.

**Comment by borekb** [comment] 2017-05-08 23:01
Duplicate of https://github.com/versionpress/versionpress/issues/1192.

**Closed** 2017-05-08 23:02 UTC
Labels: bug, duplicate, scope: dev-infrastructure
