### ISSUE TITLE
Warning Notices, et al

### ISSUE THREAD

**Issue by leepeterson** [versionpress/versionpress#1344] opened 2018-07-14 22:42 UTC
First, the `webuiPopover` method supplied in the local dev build is interfering with some plugins, breaking functionality. Console shows `Uncaught TypeError: warning.webuiPopover is not a function` when I attempt to use the [Pods Visualize](https://github.com/pods-framework/pods-visualize) plugin. Ironically, I was going to use the Pods Visualize plugin to help me view the relationships between database entities in Pods in order to create custom schema.yml files for VersionPress.

Second, while it's a good thing to remind developers that VersionPress hasn't been tested with all plugins, the list of plugins actually tested with VersionPress compared to the sheer number of possible plugins one might find listed in a Plugins table in WP means that these reminders show up everywhere.

Furthermore, displaying "VersionPress running" in bright orange text alongside the user profile name — and displaying these "warning", "preview release", "not fully supported" messages in a popover — is an excellent way to prompt doubt in my client's minds, wondering exactly how stable their website is and keeping them in a state of constant worry that some change they make might break their costly investment.

I think it's safe to assume that any developer wishing to install, configure and rely on VersionPress as a website's workflow backbone will remember that they chose to use a Developer Preview solution and shouldn't need to be reminded at every turn.

This shotgun approach to delivering warning notices and reminders everywhere possible seems to be more of a UX anti-pattern, and it's already causing breakage in long-standing solutions such as Pods Visualize. 

My vote is to completely disable all of these warning notices and offer developers the choice to remind themselves during the outset of configuring VersionPress. Should they find themselves in a pickle when some solution isn't fully integrated, well, that's why we have GitHub Issues, VP Docs, Gitter, etc.

**Comment by borekb** [comment] 2018-07-15 08:38
Hi @leepeterson, thanks for the feedback, it's well articulated.

> First, the `webuiPopover` method supplied in the local dev build is interfering with some plugins, breaking functionality. Console shows `Uncaught TypeError: warning.webuiPopover is not a function` when I attempt to use the [Pods Visualize](https://github.com/pods-framework/pods-visualize) plugin.

This seems like a bug, @pavelevap, could you please confirm and create a technical issue for that?

> Second, while it's a good thing to remind developers that VersionPress hasn't been tested with all plugins, the list of plugins actually tested with VersionPress compared to the sheer number of possible plugins one might find listed in a Plugins table in WP means that these reminders show up everywhere.

It's true that maybe this feature could be turned off until we have the online repository for plugin definitions (#1243). Right now, the lists are hardcoded [here](https://github.com/versionpress/versionpress/blob/d867edc36512222ab24a6dc60b91775a0f12b758/plugins/versionpress/src/Utils/RequirementsChecker.php#L27-L37) which obviously doesn't scale and is just a small example.

> Furthermore, displaying "VersionPress running" in bright orange text alongside the user profile name — and displaying these "warning", "preview release", "not fully supported" messages in a popover — is an excellent way to prompt doubt in my client's minds, wondering exactly how stable their website is and keeping them in a state of constant worry that some change they make might break their costly investment.
> 
> I think it's safe to assume that any developer wishing to install, configure and rely on VersionPress as a website's workflow backbone will remember that they chose to use a Developer Preview solution and shouldn't need to be reminded at every turn.

I've got a couple of thoughts around this:

- I think that there should be warnings. VersionPress _can_ be dangerous to the site which many people don't realize. I mean, my assumption as a user is that when some plugin misbehaves, I can simply disable it and all is fine; it's not the case with VersionPress.
- I agree that there could be a way to hide the warnings. At this point, I'd like to make it a "strong opt-in" like having a `VP_HIDE_WARNINGS_I_KNOW_WHAT_I_AM_DOING` constant.
- Quite reasonable could be to only warn during risky operations such as undo or pull. That would hide warnings most of the time but they would still be there at the crucial moments. What do you think?

**Comment by pavelevap** [comment] 2018-11-08 20:06
Finally, I was able to reproduce and it seems to me that it is not problem on VersionPress side.

[Pods Visualize](https://github.com/pods-framework/pods-visualize) is using [JointJS](https://github.com/clientIO/joint) library, but very old version 0.8.1. But in this version is also bundled and minified basic jQuery 2.0.3 directly in [joint.min.js](https://github.com/pods-framework/pods-visualize/blob/master/includes/jointjs/joint.min.js) file. So, when Pods Visualize calls this file, another jQuery (except WordPress core version) is loaded and it leads to conflict.

Authors of JointJS started (probably [here](https://github.com/clientIO/joint/pull/160)) to use standard Composer dependencies and unbundled jQuery in 0.9.4 version. After updating to this version, reported `Uncaught TypeError` also disappeared.

How to solve this conflict:
- Update Pods Visualize to JointJS 0.9.4 or use file [joint.nojquery.min.js](https://github.com/clientIO/joint/tree/v0.8.1/dist) from 0.8.1 (if this is the only compatible version for Pods Visualize).
- VersionPress could add higher priority (more than 10) [here](https://github.com/versionpress/versionpress/blob/4.0-beta/plugins/versionpress/setup-hooks.php#L855) to load [WebUI-Popover](https://github.com/sandywalker/webui-popover) library later than JointJS creates conflict with bundled jQuery. But I do not think that any action is needed here, because conflict is obviously caused by obsolete plugin.

As regards "VersionPress running" notice:
- I think this warning is OK for now. VersionPress can be dangerous, especially when using with plugins.
- This warning will be updated with online repository for plugin definitions.
- This warning is displayed [only to administrators](https://github.com/versionpress/versionpress/blob/4.0-beta/plugins/versionpress/setup-hooks.php#L813) (not editors or other user roles) and every administrator (who can use VersionPress) **should know about the risks**.

I suggest to close this issue, no action needed. @borekb

**Comment by borekb** [comment] 2018-11-08 21:03
Thanks, @pavelevap, let's wait if @leepeterson has anything to add.

**Comment by pavelevap** [comment] 2019-04-12 20:24
I am closing this issue for now, please reopen if there is anything new.

**Closed by pavelevap** 2019-04-12 20:24 UTC
Labels: plugin support, support
