### ISSUE TITLE
Flush 'updates available' cache on `wp vp pull`

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#1069] opened 2016-05-28 12:46 UTC
There's a small bug in VP 3.x. Steps to reproduce:
1. Activate VersionPress on a site where some plugin updates are available
2. `wp vp clone` to another environment
3. Update there
4. Pull the change to the original environment

Currently, the update notification is still there; it should be flushed.

**Comment by pavelevap** [comment] 2019-03-08 20:37
Closing as a duplicate of #1289.

**Closed by pavelevap** 2019-03-08 20:37 UTC
Labels: improvement, scope: core
