### ISSUE TITLE
PHP Fatal Error in php_errorlog 

### ISSUE THREAD

**Issue by danmaby** [versionpress/versionpress#1141] opened 2016-10-12 09:38 UTC
Hi, running 4.0-alpha1 on a vanilla 4.6.1 WP and seeing the following in `php_errorlog` and `wp-admin/php_errorlog` 

`[12-Oct-2016 01:31:44 UTC] PHP Fatal error: Uncaught Error: Call to undefined method VersionPress\ChangeInfos\UntrackedChangeInfo::getScope() in /public_html/wp-content/plugins/versionpress/src/Utils/UninstallationUtil.php:40
Stack trace:`
`#0 /public_html/wp-content/plugins/versionpress/setup-hooks.php(81): VersionPress\Utils\UninstallationUtil::uninstallationShouldRemoveGitRepo()`
`#1 /public_html/wp-includes/plugin.php(235): {closure}(true)`
`#2 /public_html/wp-admin/includes/class-wp-automatic-updater.php(117): apply_filters('automatic_updat...', true, '/home/therightt...')`
`#3 /public_html/wp-admin/includes/class-wp-automatic-updater.php(148): WP_Automatic_Updater->is_vcs_checkout('/home/therightt...')`
`#4 /public_html/wp-admin/includes/class-wp-automatic-updater.php(284): WP_Automatic_Updater->should_update('translation', Object(stdClass), '/home/therightt...')`
`#5 /public_html/wp-admin/includes/class-wp-automa in /home/therighttospeak/public_html/wp-content/plugins/versionpress/src/Utils/UninstallationUtil.php on line 40`

**Comment by borekb** [comment] 2016-10-12 11:39
Hi Dan! Good to see you're trying out VersionPress, bad to see we've got a bug in the current alpha :(

The reason is, most likely, that there was already an existing Git repo in the site root with commits created manually (not by VersionPress). That should be a supported scenario but there's a bug in the current code, we'll fix it. As a workaround, can you try VP on a completely empty site, with no previous Git repo. That should work fine.

**Comment by JanVoracek** [comment] 2017-06-07 09:28
Duplicate of #1183.

**Closed by JanVoracek** 2017-06-07 09:28 UTC
Labels: bug, scope: core
