### ISSUE TITLE
Errors during clone or merge

### ISSUE THREAD

**Issue by simcomp2003** [versionpress/versionpress#1345] opened 2018-07-14 23:03 UTC
During clone this happens, i pasted here just some part of lines. Also when i try merge same error appears.

Success: Access rules can be installed
PHP Warning:  arsort() expects parameter 1 to be array, null given in /home/********/staging/wp-includes/plugin.php on line 656
PHP Warning:  Invalid argument supplied for foreach() in /home/********/staging/wp-includes/plugin.php on line 657
Success: Database tables created
Success: VersionPress tables created
Success: Git merge driver added
PHP Warning:  syntax error, unexpected '=' in Unknown on line 4
 in /home/********/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 165
PHP Warning:  Invalid argument supplied for foreach() in /home/********/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 397
PHP Warning:  syntax error, unexpected '=' in Unknown on line 4
 in /home/********/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 165
PHP Warning:  Invalid argument supplied for foreach() in /home/********/staging/wp-content/plugins/versionpress/src/Storages/Serialization/IniSerializer.php on line 397
Success: Database synchronized
Success: All done. Clone created here

So after all this i check database and User ID is messed totally in cloned table. Question is if I do some work on staging and later merge to production all users id will be messed also. I tested this and user is removed after merge!

We have big question here is cloning works at all because we dont have "cloned" database properly!

**Comment by borekb** [comment] 2018-07-15 08:10
Hi @simcomp2003, could you please post this to [`versionpress/support`](https://github.com/versionpress/support) as it might be an incompatibility with some plugin. Thanks!

**Comment by pavelevap** [comment] 2018-11-07 13:05
This is not the first time for this particular error to appear, but I was not able to reproduce it yet:

- #1103
- https://github.com/versionpress/support/issues/48#issuecomment-222257339
- https://github.com/versionpress/support/issues/133

All are related to `Iniserializer.php`, particularly here:

https://github.com/versionpress/versionpress/blob/4.0-beta/plugins/versionpress/src/Storages/Serialization/IniSerializer.php#L165

It is probably related to some plugin/theme data incompatibility, but we have to wait for testing sample to debug it :-(

Related: #912

I am closing this for now, please reopen if you have any additional info.

**Closed by pavelevap** 2018-11-07 13:05 UTC
Labels: support
