### ISSUE TITLE
Ignoring portions of serialized data (?)

### ISSUE THREAD

**Issue by borekb** [versionpress/versionpress#607] opened 2015-12-30 21:34 UTC
An idea from Robert Iseley sent to our email on 30 Dec 2015:

> Second is same serialized data annoyances on every push/pull. There seem to be plugins that put their plugin update "checked time" into the options table vs a transient. /cry I am probably going to put these options into the git ignore list. But have you thought about breaking down serialized data in separate files? This would allow users to put specific serialized options on ignore vs the whole thing. Another use for this would be for plugins that use different keys per site usage.

**Comment by borekb** [comment] 2016-05-10 14:53
This would be quite hard to support because leaving out a portion of a serialized value may lead to a state where the option (or whatever) cannot be deserialized to a working object, and the site could break. Moving this to a backlog, hopefully, plugin authors would not put random data into serialized values that should be version-controlled.

**Comment by pavelevap** [comment] 2019-03-07 21:03
Closing as a duplicate of #1350.

**Closed by pavelevap** 2019-03-07 21:03 UTC
Labels: feature, scope: core, significant
